### ISSUE TITLE
pthreads missing

### ISSUE THREAD

**Issue by maesoser** [RagnarJensen/PiLEDlights#2]
```
gcc -Wall -O3 -o netledPi netledPi.c -lwiringPi -lpthread
gcc -Wall -O3 -o hddledPi hddledPi.c -lwiringPi -lpthread
gcc -Wall -O3 -o actledPi actledPi.c -lpthread
```

**Comment by RagnarJensen** [comment]
The programs are not threaded. -lpthread is not needed.

Tested today on
Linux foobar 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
with
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)

**Comment by maesoser** [comment]
That's true, I didn't check the headers on your *.c files. The error was on the [modified WiringPi library for Orange Pi](https://github.com/zhaolei/WiringOP)

Sorry about that!

**Comment by RagnarJensen** [comment]
No worries :-)
