### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by FabioHPT** [RagnarJensen/PiLEDlights#4]
Hello, i installed the script as described just to have the cativity led.... i wired the led to wiringpi pin 10 i can see the led light but nothing more..... the service running without any problem.... what can be wrong ?
Thanks

root@raspberrypi:~# sudo systemctl status hddledPi.service
● hddledPi.service - hddledPi mass storage activity indicator
   Loaded: loaded (/etc/systemd/system/hddledPi.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-05-17 01:33:37 BST; 54s ago
  Process: 331 ExecStart=/usr/local/bin/hddledPi -d -p 10 (code=exited, status=0/SUCCESS)
 Main PID: 337 (hddledPi)
    Tasks: 1 (limit: 4158)
   Memory: 472.0K
   CGroup: /system.slice/hddledPi.service
           └─337 /usr/local/bin/hddledPi -d -p 10

May 17 01:33:37 raspberrypi systemd[1]: Starting hddledPi mass storage activity indicator...
May 17 01:33:37 raspberrypi systemd[1]: Started hddledPi mass storage activity indicator.

**Comment by RagnarJensen** [comment]
Hi!
You will probably have to update the WiringPi libraries.
I have just tested with a fresh Raspbian install on a Pi 4B, and that installed WiringPi version 2.50.

I had to upgrade WiringPi to version 2.52 to get hddledPi to work.

http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/

Cheers, Ragnar
