### ISSUE TITLE
All pins are not accessible

### ISSUE THREAD

**Issue by PPCM** [RagnarJensen/PiLEDlights#6]
Hello,

Surely because you use wiringPi, but all pins are not accessible
Using default pin config, it works.
But in my project, I need to use GPIO 21 (pin 40) of my Raspi 4 and I wasn't able to find the right wiringPi pin

Any idea?

**Comment by kencormack** [comment]
Pin 40 is WiringPi 29

**Comment by RagnarJensen** [comment]
@kencormack Thank you :-)
